# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

  
- task: AzureVmssDeployment@0
  inputs:
    azureSubscription: 'ca-jagord-demo-test(f9b5da45-54cc-42d3-a58b-87adf6ad27ad)'
    action: 'Update image'
    vmssName: 'vmclock'
    vmssOsType: 'Linux'
    imageUrl: '/subscriptions/f9b5da45-54cc-42d3-a58b-87adf6ad27ad/resourceGroups/vmclock/providers/Microsoft.Compute/images/vmclockimg'
    customScriptsDirectory: '/root'
    customScript: 'bash install.sh'
    customScriptsStorageAccount: 'vmdeployclock'