apiVersion: v1
kind: Service
metadata:
  name: react-clock-basic-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: react-clock-basic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

